config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  #get 'welcome/index'

  root 'welcome#index'

  resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
    validates :first_name, :last_name, :email, :phone_number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    
    def index
        @students = Student.all
    end

    def new
        @student = Student.new
    end

    def create
        @student = Student.new(student_params)
        if @student.save
            redirect_to students_path, notice: 'Student has been created successfully'
        else
            render :new
        end
    end

    def show
        @student = Student.find(params[:id])
    end

    def edit
        @student = Student.find(params[:id])
    end

    def update
        @student = Student.find(params[:id])
        if @student.update(student_params)
            redirect_to student_path, notice: 'Student has been updated successfully'
        else
            render :edit
        end
    end

    def destroy
        @student = Student.find(params[:id])
        @student.destroy
        redirect_to students_path, notice: 'Student has been deleted successfully'
    end

    private

    def student_params
        params.require(:student).permit(:first_name,:last_name,:email,:phone_number)
    end
 end
# '@' symbol is used in controller variable if you want to display anything on browser.

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index  
        
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentMgmt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with model: student do |form| %>

    <% if @student.errors.any? %>
        <% @student.errors.full_messages.each do |message| %>
            <p><%= message %></p>
        <% end %>
    <% end %>
    <div>
        <%= form.label :first_name %><br>
        <%= form.text_field :first_name %>
    </div>

    <div>
        <%= form.label :last_name %><br>
        <%= form.text_field :last_name %>
    </div>

    <div>
        <%= form.label :email %><br>
        <%= form.email_field :email %>
    </div>

    <div>
        <%= form.label :phone_number %><br>
        <%= form.text_field :phone_number %>
    </div>
    <div>
        <%= form.submit :Submit %>
    </div>
<% end %>

app/views/students/edit.html.erb
<h1>Edit Student</h1>

<%= render "form", student: @student %>

app/views/students/index.html.erb
<p><%= notice %></p>

<h1>Listing students</h1>
<%= link_to 'New Student', new_student_path %>

<table>
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Phone Number</th>
            <th colspan="3">Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @students.each do |student| %> 
        <tr>
            <td><%= student.first_name %></td>
            <td><%= student.last_name %></td>
            <td><%= student.email %></td>
            <td><%= student.phone_number %></td>
            <td><%= link_to 'View', student %></td>
            <td><%= link_to 'Edit', edit_student_path(student) %></td>
            <td><%= link_to "Delete", student, data: 
            { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody> 
</table>
<%# '=' is used in td to display the values. But not in iteration 
because in iteration you are only defining but not displaying %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render "form", student: @student %> 

<%#= render partial: "form",locals: {student: @student}%>

app/views/students/show.html.erb
<p><%= notice %></p>

<h1>Student Details</h1>

<p><strong>First Name: </strong><%= @student.first_name %></p>
<p><strong>Last Name: </strong><%= @student.last_name %></p>
<p><strong>Email: </strong><%= @student.email %></p>
<p><strong>Phone Number: </strong><%= @student.phone_number %></p>

<%= link_to 'Back',students_path%> | <%= link_to 'Edit', edit_student_path(@student) %>

app/views/welcome/index.html.erb
<h1>Welcome to Rails</h1>